#!/usr/bin/env bash

cat <<EOF

You pull the lever...

The wall behind you rumbles and shifts.
A hidden passage is revealed:
the Hall of Mirrors.

Something glimmers inside...

EOF

mv .hall_of_mirrors hall_of_mirrors 2>/dev/null

